name: CI setup
description: Install Node, pnpm, and dependencies

inputs:
  registry-url:
    description: Optional npm registry URL used for publish authentication.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 11.10.0

    - name: Install Node
      if: ${{ inputs['registry-url'] == '' }}
      uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install Node
      if: ${{ inputs['registry-url'] != '' }}
      uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        registry-url: ${{ inputs['registry-url'] }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
